sonar.projectKey=smart-pest-trap-aiot
sonar.projectName=Smart Pest Trap AIoT
sonar.sources=src
sonar.exclusions=node_modules/**, dist/**, **/*.css
sonar.javascript.environments=browser
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**, dist/**, **/*.css, .github/**